GET http://localhost:8080/category

###
POST http://localhost:8080/category
Content-Type: application/json

{
    "name": ""
}

###
GET http://localhost:8080/product

###
POST http://localhost:8080/product
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description 1",
    "price": 10.0,
    "category_id": "5ce585a3-fef3-427f-843b-0eadd8558230",
    "image_url": "http://localhost:9000/products/1.png"
}


###
GET http://localhost:8080/product/770ca038-33d1-4047-9962-b61e5c502189

###
GET http://localhost:8080/product/category/efba52a5-b6b7-463b-b78a-ccc5c094fbbb

###
GET http://localhost:8080/product/category/efba52a5-b6b7-463b-b78a-ccc5c094fbbb